version: '2.1'

services:

  hashing-svc:
    container_name: hashing-svc
    build: ./hashing_svc
    ports:
      - '8002:3002'
    environment:
      - PORT=3002
    healthcheck:
      test: exit 0
  
  client-svc:
    container_name: client-svc
    build: ./client_svc
    ports:
      - '8001:3001'
    environment:
      - HASHING_SVC_URL=http://hashing-svc:3002
      - PORT=3001
    links:
      - hashing-svc
